[package]
name = "oatui"
version = "0.1.0"
edition = "2021"

[dependencies]
openapiv3 = "2"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
anyhow = "1"
thiserror = "2"
